export const paypalCurrencies = [
  { currency: 'AUD', currencySymbol: '$', type: 'PAYPAL' },
  { currency: 'BRL', currencySymbol: 'R$', type: 'PAYPAL' },
  { currency: 'CAD', currencySymbol: '$', type: 'PAYPAL' },
  { currency: 'CZK', currencySymbol: 'Kč', type: 'PAYPAL' },
  { currency: 'DKK', currencySymbol: 'kr', type: 'PAYPAL' },
  { currency: 'EUR', currencySymbol: '€', type: 'PAYPAL' },
  { currency: 'HKD', currencySymbol: '$', type: 'PAYPAL' },
  { currency: 'HUF', currencySymbol: 'Ft', type: 'PAYPAL' },
  { currency: 'INR', currencySymbol: '₹', type: 'PAYPAL' },
  { currency: 'ILS', currencySymbol: 'ع.د', type: 'PAYPAL' },
  { currency: 'JPY', currencySymbol: '¥', type: 'PAYPAL' },
  { currency: 'MYR', currencySymbol: 'RM', type: 'PAYPAL' },
  { currency: 'MXN', currencySymbol: '$', type: 'PAYPAL' },
  { currency: 'TWD', currencySymbol: '$', type: 'PAYPAL' },
  { currency: 'NZD', currencySymbol: '$', type: 'PAYPAL' },
  { currency: 'NOK', currencySymbol: 'kr', type: 'PAYPAL' },
  { currency: 'PHP', currencySymbol: '₱', type: 'PAYPAL' },
  { currency: 'PLN', currencySymbol: 'zł', type: 'PAYPAL' },
  { currency: 'GBP', currencySymbol: '£', type: 'PAYPAL' },
  { currency: 'RUB', currencySymbol: '₽', type: 'PAYPAL' },
  { currency: 'SGD', currencySymbol: '$', type: 'PAYPAL' },
  { currency: 'SEK', currencySymbol: 'kr', type: 'PAYPAL' },
  { currency: 'CHF', currencySymbol: 'Fr', type: 'PAYPAL' },
  { currency: 'THB', currencySymbol: '฿', type: 'PAYPAL' },
  { currency: 'USD', currencySymbol: '$', type: 'PAYPAL' }
]
