export const PAYPAL_ALLOWED_CURRENCIES = [
  { currency: "AUD", currency_symbol: "$", type: "PAYPAL" },
  { currency: "BRL", currency_symbol: "R$", type: "PAYPAL" },
  { currency: "CAD", currency_symbol: "$", type: "PAYPAL" },
  { currency: "CZK", currency_symbol: "Kč", type: "PAYPAL" },
  { currency: "DKK", currency_symbol: "kr", type: "PAYPAL" },
  { currency: "EUR", currency_symbol: "€", type: "PAYPAL" },
  { currency: "HKD", currency_symbol: "$", type: "PAYPAL" },
  { currency: "HUF", currency_symbol: "Ft", type: "PAYPAL" },
  { currency: "INR", currency_symbol: "₹", type: "PAYPAL" },
  { currency: "ILS", currency_symbol: "ع.د", type: "PAYPAL" },
  { currency: "JPY", currency_symbol: "¥", type: "PAYPAL" },
  { currency: "MYR", currency_symbol: "RM", type: "PAYPAL" },
  { currency: "MXN", currency_symbol: "$", type: "PAYPAL" },
  { currency: "TWD", currency_symbol: "$", type: "PAYPAL" },
  { currency: "NZD", currency_symbol: "$", type: "PAYPAL" },
  { currency: "NOK", currency_symbol: "kr", type: "PAYPAL" },
  { currency: "PHP", currency_symbol: "₱", type: "PAYPAL" },
  { currency: "PLN", currency_symbol: "zł", type: "PAYPAL" },
  { currency: "GBP", currency_symbol: "£", type: "PAYPAL" },
  { currency: "RUB", currency_symbol: "₽", type: "PAYPAL" },
  { currency: "SGD", currency_symbol: "$", type: "PAYPAL" },
  { currency: "SEK", currency_symbol: "kr", type: "PAYPAL" },
  { currency: "CHF", currency_symbol: "Fr", type: "PAYPAL" },
  { currency: "THB", currency_symbol: "฿", type: "PAYPAL" },
  { currency: "USD", currency_symbol: "$", type: "PAYPAL" },
];
